### ISSUE TITLE
Latest images on Docker Hub use masked sys-libs/glibc-2.32-r2

### ISSUE THREAD

**Issue by srcshelton** [gentoo/gentoo-docker-images#101]
... and are more than 3 months old :(

Any chance of an update, please?

**Comment by TerraTech** [comment]
Until #97 is fixed, I've been using:  [ksmanis/stage3](https://hub.docker.com/r/ksmanis/stage3/tags?page=1&ordering=last_updated)

**Comment by KSmanis** [comment]
#97 was just fixed.

**Comment by KSmanis** [comment]
```
$ docker run --rm gentoo/stage3:20210214 qlist -IRv glibc
sys-libs/glibc-2.32-r6::gentoo
```

Let's close?

**Comment by ultrabug** [comment]
<3
