### ISSUE TITLE
Musl containers incorrectly configured.

### ISSUE THREAD

**Issue by LinoBigatti** [gentoo/gentoo-docker-images#103]
Container builds for ``stage3-amd64-musl-vanilla`` and ``stage3-amd64-musl-hardened`` seem to be missing the ::musl overlay required for musl-specific patches. This prevents some packages from being correctly compiled. It is a small fix from the user side, but it requires command execution which might not be ideal for containers.

**Comment by KSmanis** [comment]
I am not familiar with musl on Gentoo, but shouldn't this be handled by the upstream stage3 tarballs?

**Comment by LinoBigatti** [comment]
I have browsed around for a bit on the musl docs, and the user is expected to configure the overlay manually. Sorry for the confusion. However, I still think this could be done from the image build script as an "extra" step, as to be as drop in as posible. Therefore, from now on this should be treated as a feature request, not a bug. (Not sure if you have a special label for that).
Again, sorry for the confusion.
