### ISSUE TITLE
[Feature Request] gentoo/catalyst: new docker image

### ISSUE THREAD

**Issue by oxr463** [gentoo/gentoo-docker-images#113]
Could we get a catalyst image? I tried creating my own, but I ran into a lot of issues.

Not sure if this is the best place, but it doesn't look like the GitHub mirror is accepting issues, https://github.com/gentoo/catalyst/issues

Reference(s):
- https://github.com/oxr463/gentoo-dotfiles/issues/2
- https://github.com/oxr463/gentoo-dotfiles/issues/3
- https://github.com/oxr463/gentoo-dotfiles/issues/4

**Comment by reavessm** [comment]
I am also trying to create a catalyst container and also running into issues.  +1 to this request

**Comment by KSmanis** [comment]
What would a catalyst image involve apart from emerging catalyst?

The referenced issues seem related to the default seccomp profile for Docker. Specifically, [the `unshare` syscall is blocked by the default profile](https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile):

Syscall | Description
-- | --
unshare | Deny cloning new namespaces for processes. Also gated by CAP_SYS_ADMIN, with the exception of unshare --user.

Therefore, you might want to run your container with `docker run --cap-add SYS_ADMIN ...` [1] or `cap_add: [SYS_ADMIN]` [2] in your `docker-compose.yml`.

[1] https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
[2] https://docs.docker.com/compose/compose-file/compose-file-v3/#cap_add-cap_drop

**Comment by ajakk** [comment]
A sledgehammer of `--privileged` might be appropriate too, I think.
