### ISSUE TITLE
Can't Pull, Redirects to private Google Container Registry

### ISSUE THREAD

**Issue by reavessm** [gentoo/gentoo-docker-images#114]
$> podman pull gentoo/stage3

✔ docker.io/gentoo/stage3:latest
Trying to pull docker.io/gentoo/stage3:latest...
Error: initializing source docker://gentoo/stage3:latest: reading manifest latest in mirror.gcr.io/gentoo/stage3: manifest unknown: Failed to fetch "latest" from request "/v2/gentoo/stage3/manifests/latest".

When browsing to https://mirror.gcr.io/gentoo/stage3 in the browser, it redirects to https://cloud.google.com/container-registry/, idk if these registries can be made public but they seem to be private

**Comment by reavessm** [comment]
Ah, yes, the 'docker.io' location was set to 'mirrors.gcr.io' with a note about dockers rate limting.  I changed it back to 'docker.io' and that fixed the issue.  Thank you for pointing me in the right direction!

**Comment by bphd** [comment]
> Ah, yes, the 'docker.io' location was set to 'mirrors.gcr.io' with a note about dockers rate limting. I changed it back to 'docker.io' and that fixed the issue. Thank you for pointing me in the right direction!

So it's a misconfiguration from package maintainer or something? That in the past GCR was a good alternative but now it just blocks any download?

**Comment by ajakk** [comment]
See also this Gentoo bug: https://bugs.gentoo.org/849863
