### ISSUE TITLE
some images are old

### ISSUE THREAD

**Issue by gyakovlev** [gentoo/gentoo-docker-images#116]
@gentoo/releng renamed most of the stages to be explicitly suffixed.

old <arch> is almost always <arch>-openrc now.

for example pulling default stage3 on ppc64le will pull a very old stage from july 2021, with pre-eapi8 portage.

since by default docker pulls :ppc64le, without explicitly specifying `gentoo/stage3:ppc64le-openrc` user gets a basically non-working portage, because many ebuilds are eapi8 already.

seems PR https://github.com/gentoo/gentoo-docker-images/pull/108 addressed this partially 
but old images are still can be pulled in by default.
can this be somehow fixed?

**Comment by KSmanis** [comment]
The `stage3-ppc64le` target was deprecated by upstream and we followed suit, as documented in the README. I don't see a point in deviating from upstream in this regard; users should upgrade to an active tag. Perhaps we need to be more explicit in the README regarding stale tags?

On a side note, there is no need to use architecture tags directly; they are more of a byproduct of our build system. `docker pull gentoo/stage3` will automatically pull the `latest` tag which will resolve to `ppc64le-openrc` on a `ppc64le` Docker host. `docker pull gentoo/stage3:systemd` will instead resolve to the `ppc64le-systemd` tag.

**Comment by gyakovlev** [comment]
hey!
yes, that's exactly what I want - `docker pull  gentoo/stage3` (if ran on ppc64le) to resolve to new image type.
in this particular case I'm the upstream - I'm on gentoo's releng team and manage ppc64le releases.

ok I re-tested and it's issue with my script
it was pulling gentoo/stage3:ppc64le and not :latest
pulling `gentoo/stage3` gets correct one

works for me, thanks.
