### ISSUE TITLE
Clean up unversioned old tags from Docker Hub

### ISSUE THREAD

**Issue by mgorny** [gentoo/gentoo-docker-images#121]
Apparently we don't have any real way of notifying people that images got renamed, so if you end up using old base images, Docker images can continue building and working successfully for a long time without anyone noticing how stale everything becomes.

Could you perhaps clean up the unversioned tags from Docker Hub after the last year's renames (7d477af788c1b206bd22d1268ed75e842d3fe00e)? I think people wouldn't mind their unupdated workflows breaking that much, given the images are really stale by now.

**Comment by ajakk** [comment]
@ultrabug I guess you're the one with the requisite accesss?

**Comment by ultrabug** [comment]
I don't see any non-versioned stage3 tag when I sort them oldest to newest @ajakk ?

**Comment by ajakk** [comment]
Then I suppose we're done!
