### ISSUE TITLE
Scheduled workflow (i.e.: building and uploading the image) has stopped

### ISSUE THREAD

**Issue by osirisinferi** [gentoo/gentoo-docker-images#122]
See https://github.com/gentoo/gentoo-docker-images/actions/workflows/build.yml:

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

Please enable the `build` workflow again, as the Docker containers haven't been updated for 2 weeks now.

**Comment by robbat2** [comment]
it's re-enabled already

**Comment by osirisinferi** [comment]
Well, it wasn't when I opened this thread :slightly_smiling_face: 

But thank you to whomever has enabled it again :+1:
