### ISSUE TITLE
Services crash status

### ISSUE THREAD

**Issue by mblasi** [gentoo/gentoo-docker-images#13]
Hi!
After building a gentoo docker container, (with the Dockerfile provided by you), all worked fine but I added some packages, like emerge mariadb and mongodb, and both cases I get crashed status when trying to start them.
Dockerfile relevant lines:
```
RUN emerge dev-vcs/git dev-vcs/mercurial net-libs/nodejs dev-db/mariadb dev-db/mongodb
# Ensure mysql and mongo are up
RUN /etc/init.d/mongodb start
#next line fails
RUN /etc/init.d/mongodb status 
```
Emerge works fine, after that I just try to start the service:

Here is the output: (no logs produced in the instance)
```
INFO     2015-05-25 14:52:22,998 containers.py:280] Step 32 : RUN /etc/init.d/mongodb start
INFO     2015-05-25 14:52:23,940 containers.py:280] ---> Running in 2d9efed0fe25
INFO     2015-05-25 14:52:24,373 containers.py:280]  * No permission to apply cgroup settings
INFO     2015-05-25 14:52:24,376 containers.py:280] * /run/mongodb: creating directory
 * /run/mongodb: correcting owner
INFO     2015-05-25 14:52:24,376 containers.py:280] * Starting mongodb ...
INFO     2015-05-25 14:52:24,378 containers.py:280] [ ok ]
INFO     2015-05-25 14:52:24,382 containers.py:280] * Caching service dependencies ... [ ok ]
INFO     2015-05-25 14:52:39,390 containers.py:280] ---> dbd1a381818b
INFO     2015-05-25 14:52:45,657 containers.py:280] Removing intermediate container 2d9efed0fe25
INFO     2015-05-25 14:52:45,657 containers.py:280] Step 33 : RUN /etc/init.d/mongodb status
INFO     2015-05-25 14:52:46,530 containers.py:280] ---> Running in 60139e970398
INFO     2015-05-25 14:52:46,805 containers.py:280]  * 
INFO     2015-05-25 14:52:46,805 containers.py:280] status: crashed
ERROR    2015-05-25 14:52:47,684 containers.py:283] The command [/bin/sh -c /etc/init.d/mongodb status] returned a non-zero code: 32
```

I have the same issue with mariadb.

I'm pretty sure it is not a bug, but I spent 2 days trying to get help on this, and no too much information about gentoo on docker :(

Thanks.
Matías.

**Comment by ChaosEngine** [comment]
It's probably related to OpenRC not playing nice with docker (or vice versa). Running mongoDB from bash gives me similar thing:
```
44702fc11317 / # /etc/init.d/mongodb start
 * Caching service dependencies ...                                                                                                                           [ ok ]
 * No permission to apply cgroup settings
 * You are attempting to run an openrc service on a
 * system which openrc did not boot.
 * You may be inside a chroot or you may have used
 * another initialization system to boot this system.
 * In this situation, you will get unpredictable results!
 * If you really want to do this, issue the following command:
 * touch /run/openrc/softlevel
 * ERROR: mongodb failed to start

```

**Comment by mblasi** [comment]
Hi, thank you for your reply.

It is also failing by trying to run the service directly.

The thing is that the instruction "RUN /usr/bin/mongod" looks like working, but there is no mongod process running in the instance after that.

I'm having exactly the same problem wiht mysql (mariadb)
If I add "RUN /etc/init.d/mysql start", runs fine, the logs show that it started perfectly, the /var/run/mysqld/mysqld.sock is created, but there is no mysql process running...
The same if I try to start it manualy: "RUN nohup /usr/bin/mysqld_safe --datadir='///var/lib/mysql' &"

Though, if I don't try to start these services from Dockerfile, go into the recently created instance, and start them manualy (/etc/init.d/mysql start, or /etc/init.d/mongodb start) they works perfectly!

It looks like something related with launching the services during Dockerfile processing...

Any idea?

**Comment by alunduil** [comment]
Hey @mblasi,

In a Dockerfile, every instruction is run in a separate container during image creation and thus the state of one to the next is not preserved.  If you want to use openrc to start your services you'll have to ensure it's configured for LXC mode and then invoke it using ``entrypoint`` or ``cmd``.  Otherwise, the recommended way is to set the ``entrypoint`` or ``cmd`` in the Dockerfile to the command you want invoked when you do a ``docker run``.

**Comment by mblasi** [comment]
Thank you very much!
You just confirmed what I was suspecting.
It was not an issue here.
Best regards,
Matías.
