### ISSUE TITLE
README: Link to DockerHub pages

### ISSUE THREAD

**Issue by mcandre** [gentoo/gentoo-docker-images#14]
Could we please:

* Publish these images to [DockerHub](https://registry.hub.docker.com/)
* Link to the DockerHub pages from this project's README.md?

**Comment by alunduil** [comment]
@mcandre,  I've just pushed the stage3-amd64 image.  Let us know about fixes and improvements.  Do you mind crafting a pull request with your recommended changes to the README?

**Comment by mcandre** [comment]
I could if I had the link to the specific image page rather than DockerHub's own homepage :P

Just add something like

```
# DockerHub

<link to the image page on DockerHub here>
```

to the README.

**Comment by mcandre** [comment]
... where on DockerHub are the images pushed? There are lots of gentoo images, not sure which one(s) were made by this project.

**Comment by ChaosEngine** [comment]
I believe it is here: https://registry.hub.docker.com/u/gentoo/stage3-amd64/

**Comment by mcandre** [comment]
https://github.com/gentoo/gentoo-docker-images/pull/17

**Comment by alunduil** [comment]
Closing since we've merged this change.  Let us know if anything else fits this bill.
