### ISSUE TITLE
link from dockerhub to github

### ISSUE THREAD

**Issue by mcandre** [gentoo/gentoo-docker-images#18]
Edit the description of https://registry.hub.docker.com/u/gentoo/stage3-amd64/ to link to this GitHub repository, to make it easier for users to find the source code for building the gentoo images.

Note that DockerHub Markdown syntax is rather subpar, requiring hyperlinks to be explicitly turned into links. The syntax would be:

```
# Source

[https://github.com/gentoo/gentoo-docker-images](https://github.com/gentoo/gentoo-docker-images)
```

**Comment by alunduil** [comment]
@mcandre sounds like a good idea to me.  Mind throwing another pull request at us?

**Comment by mcandre** [comment]
Er, I think that has to be done on the dockerhub account.

**Comment by alunduil** [comment]
It should read that from the README file.  We could move the README to README.md to use markdown as well.  I can play with it later and let you know for sure though.

**Comment by mcandre** [comment]
Ideally, DockerHub would work this way. Unfortunately, its not setup very well for this.

DockerHub has some kind of automated build process that can keep the description up to date based on version controlled files, but I've not bothered to try it.

**Comment by alunduil** [comment]
@mcandre, that's very true.  It's quite annoying when it overwrites my hand crafted descriptions with the README.  It may be looking for the README for particular images in that image's directory though.  I'll add updating READMEs to my list of things to do.

**Comment by alunduil** [comment]
Actually, now that I've looked at it what's wrong with the source link that is already on docker hub?

See the blue button on the right side of this page:
https://hub.docker.com/r/gentoo/portage/

Should we also include a link in the description if this button is available?

**Comment by ajakk** [comment]
Yeah, the links are there on DockerHub now. Not sure if they were 8 years ago, but regardless I think it's safe to close this now :)

**Comment by KSmanis** [comment]
@ajakk maybe the process could be automated, e.g., with https://github.com/marketplace/actions/docker-hub-description
