### ISSUE TITLE
Avoid duplicating build script across amd64 variate

### ISSUE THREAD

**Issue by proneetv** [gentoo/gentoo-docker-images#24]
Since all the amd64 variate mostly use the similar `build.sh` script, we should avoid duplicating it for each particular case.

The information required to generate the URL for respective amd64 variate is already available in variables `${arch}` & `${suffix}` here: https://github.com/gentoo/gentoo-docker-images/blob/master/amd64/build.sh#L23 which is the only difference across each such build script.

PS: addressing issue raised in #23

**Comment by dastergon** [comment]
Please add more information about the issue and keep the reference at the end of the description. 
It would be useful for those who weren't on the discussion to understand what was the issue and which PR solved it.

**Comment by globalcitizen** [comment]
Further to this issue, this whole area of automation for container image generation has been fairly maturely dealt with already over at `lxc-gentoo`. Recently I opened an [issue about auto-generation of docker images there](https://github.com/globalcitizen/lxc-gentoo/issues/80). Perhaps you would like to use `lxc-gentoo` script here? It is relatively well tested and supports great features like:

- Not duplicating the build script (the subject of this issue)
- Cryptographic validation

**Comment by ajakk** [comment]
This seems obsolete since, at the latest, 64f150f16c0eb0f549dd8381914f7b7e1cdd195b from years ago.
