### ISSUE TITLE
Checking stage3 signature

### ISSUE THREAD

**Issue by wking** [gentoo/gentoo-docker-images#3]
I'd recommend something like my [signature check](https://github.com/wking/dockerfile/blob/d187ff88a909275afdaefdbabae7dc5a8a3e6165/build.sh#L127) instead of blindly trusting a tarball downloaded over [insecure HTTP](https://github.com/gentoo/docker-brew-gentoo/blob/b36e1e04c996e413d2082ed90ba44a81c8e97673/amd64/build.sh#L3).  With the end goal of publishing images, it probably doesn't matter much before Docker gets signed images (dotcloud/docker#2700), but checking the sigs on the source tarball at least secures the transmission between rel-eng and our local image.

**Comment by orzel** [comment]
It's not done anymore in current sripts.

**Comment by alunduil** [comment]
@orzel are you suggesting we re-open this issue?

**Comment by ChaosEngine** [comment]
I will try to give it a shot and implement something similiar (this weekend I hope).

**Comment by orzel** [comment]
Well, i personally dont care that much, but just to provide a hint on the current status for those coming here.
