### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by dantswain** [gentoo/gentoo-docker-images#31]
As someone who might be using one or more of these images to build production code, it's really important to be able to be getting a known version of the image.

I'm not sure if this is exactly the right place to file this request since it relates more to the workflow of pushing to dockerhub, so please let me know if there is a better place to do it.

**Comment by tpetry** [comment]
+1

Without tagging the whole reproducible builds idea of docker is completely lost. I may get a different gentoo image yesterday and today which are incompatible in small things.

**Comment by mrueg** [comment]
Releases will be tagged by the daily builds
