### ISSUE TITLE
amd64-hardened-nomultilib missing from DockerHub

### ISSUE THREAD

**Issue by berney** [gentoo/gentoo-docker-images#32]
In the source here I see there is a hardened+nomultilib but on DockerHub I can only see amd64, amd64-nomultilib, and amd64-hardened.

Similarly x86 is here but missing there (also there's only one x86 profile).

**Comment by bwrega** [comment]
Vote up for this issue.
Is there a particular reason that the hardened+nomultilib profile is not included in docker repo?

**Comment by mrueg** [comment]
Added amd64-hardened-nomultilib and x86-hardened today.
