### ISSUE TITLE
Broken automated builds on docker hub

### ISSUE THREAD

**Issue by xificurk** [gentoo/gentoo-docker-images#39]
All automated builds on docker hub ( https://hub.docker.com/r/gentoo/ ) are old a couple of weeks... they used to be triggered every day, but for some reason it stopped some time around New Year.

**Comment by simonvanderveldt** [comment]
@ChaosEngine @alunduil @mrueg any idea why this is happening? The last commit in this repo is from september 2016 and the last build on the Docker Hub from januari 1st 2017, was it supposed to trigger daily or only on code change?

**Comment by mrueg** [comment]
I don't have access to dockerhub, can't tell you. @tianon might be able to take a look

**Comment by tianon** [comment]
As far as I can see in Docker Hub, the automated builds are still configured properly -- dunno if webhooks here are broken, or if something external was triggering these on a regular basis, because automated builds don't normally trigger new builds by themselves unless there's a commit (and thus a webhook, if properly configured) or a repository link (and the linked repository has a push event).

**Comment by simonvanderveldt** [comment]
@tianon Nice to see you here as well! :)

Maybe it was an update to busybox? That seems to get regular updates, including 2 months ago. Though in that case a Repository links from the gentoo image to busybox should exist.

**Comment by ChaosEngine** [comment]
theory with updated busybox checks out, it's repo changed about 2 months ago

**Comment by timeraider4u** [comment]
Any news on this issue? Following the instructions from the wiki at https://github.com/gentoo/gentoo-docker-images/wiki/Launcher-Container-Example results in an outdated docker container.
```bash
~ $ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
gentoo/stage3-amd64   latest              03bfe6984168        10 weeks ago        839.5 MB
gentoo/portage        latest              7a206e7a8d9e        10 weeks ago        493.9 MB
```
And inside the container:
```bash
d312cc30ff1f / # emerge --version
Portage 2.3.0 (python 3.4.5-final-0, default/linux/amd64/13.0, gcc-4.9.4, glibc-2.22-r4, 4.9.6-gentoo-r1 x86_64)
d312cc30ff1f / # cat /usr/portage/metadata/timestamp
Sun Jan  1 00:39:32 UTC 2017
```

**Comment by anonymous09** [comment]
Still no updates. Any suggestions?

**Comment by timeraider4u** [comment]
@anonymous09: I have found out that you can create a Gentoo docker container yourself with:
```bash
git clone https://github.com/gentoo/gentoo-docker-images
cd gentoo-docker-images
cd portage
docker build -t gentoo/portage .
cd ../amd64
docker build -t gentoo/stage3-amd64 . 
cd ../../

docker create -v /usr/portage --name portage gentoo/portage
docker run --volumes-from portage --name gentoo -it gentoo/stage3-amd64 /bin/bash
```

But of course, this is only a work-around which has several limitations: It is really slow, I have no idea how to automate it and it cannot be used to derive your own dockerfiles and so on.

**Comment by mrueg** [comment]
Updates should be rolling now daily via travis-ci.

**Comment by timeraider4u** [comment]
Thank you very, very much for fixing this issue!

From inside the container:
```bash
d4adcd82263a / # emerge --version
Portage 2.3.5 (python 3.4.5-final-0, default/linux/amd64/13.0, gcc-5.4.0, glibc-2.23-r3, 4.9.16-gentoo x86_64)
d4adcd82263a / # cat /usr/portage/metadata/timestamp.chk
Wed, 17 May 2017 00:45:01 +0000
```
