### ISSUE TITLE
"portage" image produce huge I/O every time

### ISSUE THREAD

**Issue by anonymous09** [gentoo/gentoo-docker-images#40]
Good day. I am using Gentoo images in Continuous Integration (Gitlab CI). I run docker via commands:
```
docker create -v /usr/portage --name portage gentoo/portage
docker run --volumes-from portage --name gentoo gentoo/stage3-amd64 -c "foo bar"
```
And every time first command produce huge I/O because all content from /usr/portage copying from image to container "portage".
How I can prevent it?

Can you create image without "VOLUME /usr/portage" keyword?

**Comment by simonvanderveldt** [comment]
@anonymous09 There's not a whole lot you can do. Docker is basically extracting the volume image at that point. That obviously needs to happen, so afaik there's nothing you can do about it.

**Comment by oxr463** [comment]
See also: https://github.com/presslabs/gitfs/issues/319

**Comment by ajakk** [comment]
Yeah, not much we can do as the Docker downstream, unless we see a good replacement for the way we currently recommend using the repository. Users might try fiddling with different storage backends or see if `podman` can handle things any better.

**Comment by tianon** [comment]
Oh, I think BuildKit's ability to mount content directly from another image might be useful here?

```dockerfile
# syntax=docker/dockerfile:1
FROM gentoo/stage3
RUN --mount=type=bind,from=gentoo/portage,source=/var/db/repos/gentoo,target=/var/db/repos/gentoo \
        emerge app-misc/hello
CMD ["hello"]
```

(Then built with `docker buildx build`)
