### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by lramage94** [gentoo/gentoo-docker-images#50]
Just a minor nitpick.

Using the portage container as a data volume

docker create -v /usr/portage --name myportagesnapshot gentoo/portage:latest /bin/true
docker run --volumes-from myportagesnapshot gentoo/stage-amd64:latest /bin/bash

Needs to be,
gentoo/stage-amd64:latest -> gentoo/stage3-amd64:latest

**Comment by mrueg** [comment]
Fixed by https://github.com/gentoo/gentoo-docker-images/pull/49
