### ISSUE TITLE
uclibc variants cannot be built

### ISSUE THREAD

**Issue by mhier** [gentoo/gentoo-docker-images#61]
When setting TARGET=stage3-amd64-uclibc-vanilla the script fails, because it will replace the last dash into a plus sign and it tries to download:
https://ftp-osl.osuosl.org/pub/gentoo/releases/amd64/autobuilds/latest-stage3-amd64-uclibc+vanilla.txt

This will probably also prevent the selinux variants from being built.

**Comment by dalehamel** [comment]
I also hit this, should be an easy fix. Do the maintainers accept PRs here?

**Comment by ultrabug** [comment]
Yes we do @dalehamel

**Comment by mjeveritt** [comment]
Having got the musl builds going, I'll give this a whirl too .. the patched build script should Just Work™...

**Comment by mjeveritt** [comment]
Having got the musl builds going, I'll give this a whirl too .. the patched build script should Just Work™...

**Comment by ultrabug** [comment]
@mjeveritt thx for ur help, plz report back here so we know if we can close this

**Comment by mjeveritt** [comment]
@ultrabug - struggling with github's web interface today, but I'm on it. Glad to have found the repo, and thanks for merges! :)
