### ISSUE TITLE
17.1 profile

### ISSUE THREAD

**Issue by ckonstanski** [gentoo/gentoo-docker-images#67]
A recent portage news article stated that the 17.0 profile will soon be removed and that users should switch to 17.1. When will this docker image start using 17.1?

**Comment by mjeveritt** [comment]
@KSmanis should be able to pick this one up too

**Comment by KSmanis** [comment]
This issue doesn't seem to be relevant anymore:

```
$ docker run --rm gentoo/stage3-amd64 ls -l /etc/portage/make.profile
lrwxrwxrwx 1 root root 59 Aug 23 22:29 /etc/portage/make.profile -> ../../var/db/repos/gentoo/profiles/default/linux/amd64/17.1
```

stage3 tarballs have apparently migrated to the 17.1 profile already. The Docker images merely download, verify, and extract the stage3 tarballs, so this change propagated naturally. Not much to do here.

**Comment by ultrabug** [comment]
Good catch thanks
