### ISSUE TITLE
Mount overlay as volume?

### ISSUE THREAD

**Issue by oxr463** [gentoo/gentoo-docker-images#74]
```sh
git clone https://gitlab.com/oxr463/overlay.git
docker run -v $(pwd):/usr/local/portage/rage -it gentoo/stage3-amd64 /bin/bash
```

**Comment by ultrabug** [comment]
@oxr463 what is it that you're trying to say plz?

**Comment by oxr463** [comment]
How can I easily use these images to test my personal overlay?

**Comment by simonvanderveldt** [comment]
@oxr463 like this
https://github.com/gentoo-audio/audio-overlay/blob/master/tests/emerge-ebuild.sh#L28

https://github.com/gentoo-audio/audio-overlay/blob/master/tests/resources/emerge-ebuild.sh#L34

**Comment by oxr463** [comment]
Yes, exactly what I was looking for!

**Comment by simonvanderveldt** [comment]
FYI the default location for overlays has changed, it's now `/var/db/repos/` although the old `/usr/portage` dir still works.

**Comment by oxr463** [comment]
I ran into that exact problem yesterday when I opened this issue.
