### ISSUE TITLE
Unable to unshare: EPERM

### ISSUE THREAD

**Issue by oxr463** [gentoo/gentoo-docker-images#81]
```sh
Unable to unshare: EPERM (for FEATURES="pid-sandbox")
Unable to unshare: EPERM (for FEATURES="ipc-sandbox network-sandbox pid-sandbox")
```

**Comment by TerraTech** [comment]
I just hit this today and found the following in Gentoo's Bugzilla:
[Bug 680456 - sys-apps/portage: "Unable to unshare" messages could be more specific, and could be deduplicated](https://bugs.gentoo.org/680456)

In my case, I fixed it with:  ```FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox ..."```

**Comment by houstar** [comment]
I've hit  again, is this fixed ?

**Comment by APN-Pucky** [comment]
I encountered a similar issue on my gentoo system.
FEATURE flags were insufficient.

My solution was upgrading to docker-20.10.9.

**Comment by KSmanis** [comment]
I'm afraid there is nothing to fix here. These `FEATURES` use syscalls (`unshare` by the looks of it) that are blacklisted by the default seccomp profile for Docker. You either have to disable the offending `FEATURES` or elevate the container permissions. See [this comment](https://github.com/gentoo/gentoo-docker-images/issues/113#issuecomment-1020501108) for a more elaborate description.
