### ISSUE TITLE
x86 stages failing - "Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time"

### ISSUE THREAD

**Issue by mjeveritt** [gentoo/gentoo-docker-images#85]
stage3-x86* builds are currently failing with a message:

```
Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time
PermissionError: [Errno 1] Operation not permitted
```

**Comment by tianon** [comment]
This sounds suspiciously like https://github.com/moby/moby/issues/40734, especially since it's all the 32bit architectures that are failing.
