### ISSUE TITLE
Travis CI build results not shown on commits/pull requests

### ISSUE THREAD

**Issue by KSmanis** [gentoo/gentoo-docker-images#90]
Even though the Travis CI build system is successfully triggered on every commit/pull request, its results are not shown as checks in the GitHub interface, making it unnecessarily difficult to track them.

Apparently the solution seems to be to revoke access to Travis and consequently reconnect it (possibly [using GitHub Apps](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/)). A member with admin rights would be required to do this.

Relevant reports: [[1]](https://travis-ci.community/t/6955), [[2]](https://travis-ci.community/t/7798)

**Comment by ultrabug** [comment]
I do not have such rights I'm afraid... maybe we need to ping someone in #gentoo-infra

**Comment by mgorny** [comment]
I've enabled the app, entered the beta and migrated this repo to it. FWICS, the Travis status appeared on a first commit, so it seems to be working. Please close if that's all you need, or tell me what else to do.

**Comment by KSmanis** [comment]
It seems to have been picked up properly by both commits and pull requests. Thanks!
