### ISSUE TITLE
Push access denied to docker.io/gentoo/stage3

### ISSUE THREAD

**Issue by KSmanis** [gentoo/gentoo-docker-images#95]
Latest cron job fails for all `stage3` targets with:

```
Login Succeeded
The push refers to repository [docker.io/gentoo/stage3]
9fa033b3feca: Preparing
denied: requested access to the resource is denied
```

Login succeeds and the images are properly tagged, so my guess would be that the `DOCKER_USERNAME` defined in the settings of the Travis repo (i.e., `larrythecow`) is not a collaborator in the new `stage3` Docker Hub repo. @ultrabug could you please verify? If this is not the case could you compare the configuration between the new `stage3` Docker Hub repo and the older `stage3-*` repos and find the culprit?

**Comment by ultrabug** [comment]
Indeed sorry I missed that @KSmanis ; just added the builder role to RW to the repo

**Comment by KSmanis** [comment]
All targets were successfully pushed!
