### ISSUE TITLE
[DockerHub] Deprecation notices for old repos

### ISSUE THREAD

**Issue by KSmanis** [gentoo/gentoo-docker-images#96]
Since all `stage3` images are now pushed to a single repo, it would probably be a good idea to put up deprecation notices on all old `stage3-*` Docker Hub repos that would redirect newcomers to the new `stage3` repo and hopefully avoid confusion.

**Comment by ultrabug** [comment]
I updated the IRC channel header indeed, but I guess we should come up with a note to be added to all those repos

**Comment by KSmanis** [comment]
A simple notice would suffice:

```
# DEPRECATED
This repository has been deprecated in favor of the [gentoo/stage3](https://hub.docker.com/r/gentoo/stage3) repository, which contains all stage3 configurations as tags. Please adjust your usages accordingly. For more information refer to GitHub issue [gentoo/gentoo-docker-images#86](https://github.com/gentoo/gentoo-docker-images/issues/86).
```

Feel free to adjust as you see fit.

**Comment by ultrabug** [comment]
Done, thanks and sorry it took so long!
