### ISSUE TITLE
Travis CI builds fail due to negative credit balance

### ISSUE THREAD

**Issue by KSmanis** [gentoo/gentoo-docker-images#97]
Travis CI builds have been disabled since yesterday with the following error:

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://travis-ci.com/organizations/gentoo/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://travis-ci.com/organizations/gentoo/plan?anchor=oss-consumption).

**Comment by ultrabug** [comment]
@robbat2 @mgorny hi

Do we have any plan/take on this from infra perspective please?

**Comment by mgorny** [comment]
I suppose it would be nice if releng included this on the machine making stages -- preferably saving unnecessary back-and-forth traffic.

**Comment by winterheart** [comment]
Maybe there option to switch Github Actions?

**Comment by MeisterP** [comment]
> Maybe there option to switch Github Actions?

Any progress here? There's even a pull request...
https://github.com/gentoo/gentoo-docker-images/pull/100

**Comment by ultrabug** [comment]
@MeisterP I'm trying to get a hold on the dockerhub credentials first with the help of @arzano

**Comment by MeisterP** [comment]
Thanks for the update :)
