### ISSUE TITLE
process_vm_readv when building software inside docker image

### ISSUE THREAD

**Issue by stebo85** [gentoo/gentoo-docker-images#98]
Dear Gentoo docker image team,

I would like to use the official docker image as a baseline for a gentoo container, but I am running into this issue when compiling for example fpc (and binutils and many more ...)

>>> Compiling source in /var/tmp/portage/dev-lang/fpc-3.0.4/work/fpcbuild-3.0.4/fpcsrc ...
make -j8 -j1 PP=/var/tmp/portage/dev-lang/fpc-3.0.4/work/lib/fpc/3.0.4/ppcx64 compiler_cycle AS=x86_64-pc-linux-gnu-as 
 * /var/tmp/portage/sys-apps/sandbox-2.20/work/sandbox-2.20/libsandbox/trace.c:do_peekstr():134: failure (Operation not permitted):
 * ISE:do_peekstr:process_vm_readv(27870, 0x00007ffc663d3670{0x00007ffb5cc28010, 0x1f7}, 1, 0x00007ffc663d3680{0x00007fffbc5d5e09, 0x1f7}, 1, 0) failed: Operation not permitted
/usr/lib/portage/python3.7/ebuild-helpers/emake: line 28: 27867 Aborted                 "${cmd[@]}"

I think the problem is that inside a docker container the seccomp security profile does not allow me to use the process_vm_readv syscall (https://docs.docker.com/engine/security/seccomp/)

For a quick test, I disabled the security option for the container with --security-opt seccomp=unconfined and things work, but this can't be a solution.

How did you get around this problem when building the original images? Is there a flag that I can set somewhere to disable the use of process_vm_readv so I can extend the image?

**Comment by KSmanis** [comment]
The upstream images merely extract the corresponding stage3 tarball; no compiling is performed.

Would you mind sharing some more information, e.g., where your Docker host is located and the part of the Dockerfile that triggers the error?

**Comment by stebo85** [comment]
Ahh, this makes sense. 

I would like to build the image on github actions in our repo here (https://github.com/NeuroDesk/caid/blob/master/recipes/samri/build.sh) 

The dockerfile is very simple and it fails on emerging the samri package on the last line (https://github.com/IBT-FMI/SAMRI):
FROM gentoo/stage3
RUN emerge --sync
RUN emerge --verbose dev-vcs/git
WORKDIR /etc/portage/repos.conf/
RUN wget https://gitweb.gentoo.org/proj/sci.git/plain/metadata/science.conf -O /etc/portage/repos.conf/science
RUN emaint sync --repo science
RUN echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf
RUN emerge -v samri --autounmask-continue


Any hints what I am doing wrong would be wonderful :)

**Comment by KSmanis** [comment]
Can you reproduce the error if you build locally? The CI environment is often the culprit for this kind of errors in my experience.

**Comment by stebo85** [comment]
Yes, I get the same error when building locally.

**Comment by KSmanis** [comment]
Indeed, I get the same error. See moby/moby#1916 and specifically its [resolution](https://github.com/moby/moby/issues/1916#issuecomment-530278444).

**Comment by stebo85** [comment]
Dear @KSmanis,

That's very helpful :) Thank you so much - I will try this.

**Comment by KSmanis** [comment]
For future reference, the following combination of Dockerfile and build commands seem to be working on an Ubuntu 18.04.5 LTS host with Docker CE 19.03.13:

```Dockerfile
# syntax=docker/dockerfile:experimental
FROM gentoo/stage3
RUN emerge --sync
RUN emerge --verbose dev-vcs/git
WORKDIR /etc/portage/repos.conf/
RUN wget https://gitweb.gentoo.org/proj/sci.git/plain/metadata/science.conf -O /etc/portage/repos.conf/science
RUN emaint sync --repo science
RUN echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf
RUN --security=insecure emerge -v samri --autounmask-continue
```

```shell
export DOCKER_CLI_EXPERIMENTAL=enabled
docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'
docker buildx build --allow security.insecure .
```

**Comment by cryptogopher** [comment]
It seems the problem has been resolved in newer version of Docker: `process_vm_readv` and `process_vm_writev` syscalls have been enabled, see: https://github.com/moby/moby/commit/d39b075302c27f77b2de413697a5aacb034d8286

As a temporary workaroud (before new Docker version will be released) you can download updated seccomp profile (https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) and specify its path as a parameter to dockerd daemon, e.g. through _/etc/docker/daemon.json_:

<pre>
{
    "seccomp-profile": "/etc/docker/seccomp-profile.json",
}
</pre>

**Comment by stebo85** [comment]
That's awesome! Thank you for letting me know. I try that :)
